{
  "formatVersion": "1.1",
  "component": {
    "group": "com.salesforce.personalization",
    "module": "lowcodemobile",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.salesforce.personalization",
          "module": "sdk",
          "version": {
            "requires": "[3.1.2,4.0.0)"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        }
      ],
      "files": [
        {
          "name": "lowcodemobile-1.2.1.aar",
          "url": "lowcodemobile-1.2.1.aar",
          "size": 74403,
          "sha512": "f196ffbff8386f129b0ada32698bee7701637f138255ddc24bc932636023d9eafd4dd1fbfce514a6b9523235bb5d331fbb09b7ed92d370f3256105bf001a3e8b",
          "sha256": "b8412d499f206e4be1d45ad627c4b2a538715961690fbe2a7ac37a0b0e277a0e",
          "sha1": "3aa3bf7c8bcce98fd52656380aee2e73966aeeb5",
          "md5": "9b8e9dceb002dbf03e75592f261429be"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit"
        },
        {
          "group": "com.salesforce.personalization",
          "module": "sdk",
          "version": {
            "requires": "[3.1.2,4.0.0)"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        }
      ],
      "files": [
        {
          "name": "lowcodemobile-1.2.1.aar",
          "url": "lowcodemobile-1.2.1.aar",
          "size": 74403,
          "sha512": "f196ffbff8386f129b0ada32698bee7701637f138255ddc24bc932636023d9eafd4dd1fbfce514a6b9523235bb5d331fbb09b7ed92d370f3256105bf001a3e8b",
          "sha256": "b8412d499f206e4be1d45ad627c4b2a538715961690fbe2a7ac37a0b0e277a0e",
          "sha1": "3aa3bf7c8bcce98fd52656380aee2e73966aeeb5",
          "md5": "9b8e9dceb002dbf03e75592f261429be"
        }
      ]
    }
  ]
}
