{
  "formatVersion": "1.1",
  "component": {
    "group": "com.salesforce.personalization",
    "module": "sdk",
    "version": "3.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.salesforce.marketingcloud",
          "module": "cdp",
          "version": {
            "requires": "[3.0.1,4.0.0)"
          }
        },
        {
          "group": "androidx.core",
          "module": "core"
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-3.1.2.aar",
          "url": "sdk-3.1.2.aar",
          "size": 441703,
          "sha512": "a845e1173a3b1d6ece33a4bc2daa79a78fcf6cc915d9e44cbde2432a14bed6096203126eea875b294966fd7def24c9ddff0d8afc6a69ee7a969e327267dc0222",
          "sha256": "ee325457780c988065f5c6e561f80640dbb016503a241e552bcfc811a8fa5455",
          "sha1": "49008173588ab36a8d052d4bd16d3ece0de4fc1c",
          "md5": "f311c7e12ef68aa9fb1cfd1375809153"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.salesforce.marketingcloud",
          "module": "cdp",
          "version": {
            "requires": "[3.0.1,4.0.0)"
          }
        },
        {
          "group": "androidx.core",
          "module": "core"
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-3.1.2.aar",
          "url": "sdk-3.1.2.aar",
          "size": 441703,
          "sha512": "a845e1173a3b1d6ece33a4bc2daa79a78fcf6cc915d9e44cbde2432a14bed6096203126eea875b294966fd7def24c9ddff0d8afc6a69ee7a969e327267dc0222",
          "sha256": "ee325457780c988065f5c6e561f80640dbb016503a241e552bcfc811a8fa5455",
          "sha1": "49008173588ab36a8d052d4bd16d3ece0de4fc1c",
          "md5": "f311c7e12ef68aa9fb1cfd1375809153"
        }
      ]
    }
  ]
}
