{
  "formatVersion": "1.1",
  "component": {
    "group": "com.salesforce.personalization",
    "module": "ootbcomponents",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.salesforce.personalization",
          "module": "lowcodemobile",
          "version": {
            "requires": "[1.2.1,2.0.0)"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit"
        }
      ],
      "files": [
        {
          "name": "ootbcomponents-1.2.1.aar",
          "url": "ootbcomponents-1.2.1.aar",
          "size": 105957,
          "sha512": "71279f16cebaf4be57dad153be3f7adcf664dd5270373c303d743d78302243b8fc54ce86d95de41af4d486f1b4593b6dea272c17f705ba425302203f133b759e",
          "sha256": "ec5dcfc11abccf37f243aa45b59f65b30f4728d39278aec74d54b5522182e257",
          "sha1": "6738532af4bb4d785109092ac3a8621465462c31",
          "md5": "2f8015628bf809c1a77e2e5e713f6c4c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose-base"
        },
        {
          "group": "com.salesforce.personalization",
          "module": "lowcodemobile",
          "version": {
            "requires": "[1.2.1,2.0.0)"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit"
        }
      ],
      "files": [
        {
          "name": "ootbcomponents-1.2.1.aar",
          "url": "ootbcomponents-1.2.1.aar",
          "size": 105957,
          "sha512": "71279f16cebaf4be57dad153be3f7adcf664dd5270373c303d743d78302243b8fc54ce86d95de41af4d486f1b4593b6dea272c17f705ba425302203f133b759e",
          "sha256": "ec5dcfc11abccf37f243aa45b59f65b30f4728d39278aec74d54b5522182e257",
          "sha1": "6738532af4bb4d785109092ac3a8621465462c31",
          "md5": "2f8015628bf809c1a77e2e5e713f6c4c"
        }
      ]
    }
  ]
}
